### ISSUE TITLE
Professional Development Guide

### ISSUE THREAD

**Issue by rufuspollock** [atomatichq/pm#17]
# Professional development list

*What is the biggest thing holding you back right now in being excellent and making an even bigger contribution at Datopian?*

=> Brainstorm areas (and then refine that list)

For each Area you need to do Research and Analysis

* Example of not working - hence need for development
* Description of what it is (e.g. if area is "Planning" write down what is "Planning")
* Example of it working well (can be someone/somewhere else)
* Identify Tasks e.g.
  * Learning - what do read, look at etc (maybe even a task to research this)
  * Practice - what practices will you do
  * Testing - how will you test this?
  * ...
* Identify Acceptance Criteria - these are basically your goals (SMART)
  * How would you know you were better at this
  * How would you know you were great at this
* Estimate (individual stages perhaps)
* Outputs
  * A record of outputs from doing this work

Acceptance criteria for this research part!

* [ ] Description as above
* [ ] Set of tasks
* [ ] Plan for development with schedule
    * [ ] Acceptance criteria / goals for overall item - listed in the metrics sheet

Suggested structure for your plan:

```
# {Area that you are working on}

Paragraph explaining what it is

* Examples of not working and working

## Acceptance Criteria

## Tasks

## Outputs

*What you have produced as you go along. E.g. notes, write-ups, what you read.

This is important for you and also important because other people may benefit
from what you have found and learnt*
```
